import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE-ERR:', m.text().slice(0, 200)); });
page.on('pageerror', (e) => console.log('PAGEERR:', String(e).slice(0, 300)));
page.on('requestfailed', (r) => console.log('REQ-FAIL:', r.url().slice(0, 120), r.failure()?.errorText));
await page.goto('http://localhost:5199', { waitUntil: 'networkidle' });
await page.fill('input[placeholder^="transmit"]', 'Process migration PR #4 in itssaharsh/countersign: commit and post the receipt.');
await page.click('button:has-text("SEND")');
await page.waitForTimeout(12000);
const feed = await page.evaluate(() => document.body.innerText.slice(0, 1600));
console.log('FEED:\n', feed);
await browser.close();
